### ISSUE TITLE
Read twitter handle of sender to reply tweet vouching for a friend

### ISSUE THREAD

**Issue by davidbeermann** [schokotron/schokotron#3]
When a person vouches for a friend the reply does not contain the sender's twitter handle. Therefore, Twitter ignores the reply tweet id and does not associate the welcoming tweet to the tweet of the person vouching for a new friend.

**Comment by davidbeermann** [comment]
@GnrGnr How should we add the twitter handle to the response?

**Comment by GnrGnr** [comment]
Replying to a Tweet and including "friend" does work imho. But if you reply to a conversation with multiple participants, Schokotron (correctly) identifies ALL users replied to as users to include as friends - even though users are only mentioned in the "header" and not the "body" text of the tweet.

In the below example, all users have been added as a friend.
![screen shot 2017-12-14 at 11 27 00](https://user-images.githubusercontent.com/8639993/33987638-dffd6b3a-e0c1-11e7-9225-66fbb4b94ed8.png)

Easiest way to solve this would be to exclude the "header" (is it called like that on Twitter?) from parsing and only focus on the b"body" of the Tweet.

**Comment by scepticulous** [comment]
closing in favor of #57
